// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Backend
func (this *Backend) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend
func (this *Backend) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination
func (this *Backend_Destination) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination
func (this *Backend_Destination) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_FullyQualifiedDomainName
func (this *Backend_Destination_FullyQualifiedDomainName) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_FullyQualifiedDomainName
func (this *Backend_Destination_FullyQualifiedDomainName) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_ServicePort
func (this *Backend_Destination_ServicePort) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_ServicePort
func (this *Backend_Destination_ServicePort) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_ServicePort_TLS
func (this *Backend_Destination_ServicePort_TLS) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_ServicePort_TLS
func (this *Backend_Destination_ServicePort_TLS) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_ServicePort_TLS_CertificateReference
func (this *Backend_Destination_ServicePort_TLS_CertificateReference) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_ServicePort_TLS_CertificateReference
func (this *Backend_Destination_ServicePort_TLS_CertificateReference) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_ServicePort_TLS_CertificateAuthorityReference
func (this *Backend_Destination_ServicePort_TLS_CertificateAuthorityReference) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_ServicePort_TLS_CertificateAuthorityReference
func (this *Backend_Destination_ServicePort_TLS_CertificateAuthorityReference) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_ServicePort_TLS_FrontendTLS
func (this *Backend_Destination_ServicePort_TLS_FrontendTLS) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_ServicePort_TLS_FrontendTLS
func (this *Backend_Destination_ServicePort_TLS_FrontendTLS) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Destination_ServicePort_TLS_BackendTLS
func (this *Backend_Destination_ServicePort_TLS_BackendTLS) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Destination_ServicePort_TLS_BackendTLS
func (this *Backend_Destination_ServicePort_TLS_BackendTLS) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend_Extension
func (this *Backend_Extension) MarshalJSON() ([]byte, error) {
	str, err := BackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend_Extension
func (this *Backend_Extension) UnmarshalJSON(b []byte) error {
	return BackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	BackendMarshaler   = &jsonpb.Marshaler{}
	BackendUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
