// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Backend within kubernetes types, where deepcopy-gen is used.
func (in *Backend) DeepCopyInto(out *Backend) {
	p := proto.Clone(in).(*Backend)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend. Required by controller-gen.
func (in *Backend) DeepCopy() *Backend {
	if in == nil {
		return nil
	}
	out := new(Backend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend. Required by controller-gen.
func (in *Backend) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination) DeepCopyInto(out *Backend_Destination) {
	p := proto.Clone(in).(*Backend_Destination)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination. Required by controller-gen.
func (in *Backend_Destination) DeepCopy() *Backend_Destination {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination. Required by controller-gen.
func (in *Backend_Destination) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_FullyQualifiedDomainName within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_FullyQualifiedDomainName) DeepCopyInto(out *Backend_Destination_FullyQualifiedDomainName) {
	p := proto.Clone(in).(*Backend_Destination_FullyQualifiedDomainName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_FullyQualifiedDomainName. Required by controller-gen.
func (in *Backend_Destination_FullyQualifiedDomainName) DeepCopy() *Backend_Destination_FullyQualifiedDomainName {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_FullyQualifiedDomainName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_FullyQualifiedDomainName. Required by controller-gen.
func (in *Backend_Destination_FullyQualifiedDomainName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort) DeepCopyInto(out *Backend_Destination_ServicePort) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort. Required by controller-gen.
func (in *Backend_Destination_ServicePort) DeepCopy() *Backend_Destination_ServicePort {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort. Required by controller-gen.
func (in *Backend_Destination_ServicePort) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_TLS within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_TLS) DeepCopyInto(out *Backend_Destination_ServicePort_TLS) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_TLS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS) DeepCopy() *Backend_Destination_ServicePort_TLS {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_TLS_CertificateReference within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_TLS_CertificateReference) DeepCopyInto(out *Backend_Destination_ServicePort_TLS_CertificateReference) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_TLS_CertificateReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_CertificateReference. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_CertificateReference) DeepCopy() *Backend_Destination_ServicePort_TLS_CertificateReference {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_TLS_CertificateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_CertificateReference. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_CertificateReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_TLS_CABundleReference within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_TLS_CABundleReference) DeepCopyInto(out *Backend_Destination_ServicePort_TLS_CABundleReference) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_TLS_CABundleReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_CABundleReference. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_CABundleReference) DeepCopy() *Backend_Destination_ServicePort_TLS_CABundleReference {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_TLS_CABundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_CABundleReference. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_CABundleReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_TLS_FrontendTLS within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_TLS_FrontendTLS) DeepCopyInto(out *Backend_Destination_ServicePort_TLS_FrontendTLS) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_TLS_FrontendTLS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_FrontendTLS. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_FrontendTLS) DeepCopy() *Backend_Destination_ServicePort_TLS_FrontendTLS {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_TLS_FrontendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_FrontendTLS. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_FrontendTLS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_TLS_BackendTLS within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_TLS_BackendTLS) DeepCopyInto(out *Backend_Destination_ServicePort_TLS_BackendTLS) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_TLS_BackendTLS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_BackendTLS. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_BackendTLS) DeepCopy() *Backend_Destination_ServicePort_TLS_BackendTLS {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_TLS_BackendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_TLS_BackendTLS. Required by controller-gen.
func (in *Backend_Destination_ServicePort_TLS_BackendTLS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_ProtocolOptions within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_ProtocolOptions) DeepCopyInto(out *Backend_Destination_ServicePort_ProtocolOptions) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_ProtocolOptions)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_ProtocolOptions. Required by controller-gen.
func (in *Backend_Destination_ServicePort_ProtocolOptions) DeepCopy() *Backend_Destination_ServicePort_ProtocolOptions {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_ProtocolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_ProtocolOptions. Required by controller-gen.
func (in *Backend_Destination_ServicePort_ProtocolOptions) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_ServicePort_ProtocolOptions_MCPOptions within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_ServicePort_ProtocolOptions_MCPOptions) DeepCopyInto(out *Backend_Destination_ServicePort_ProtocolOptions_MCPOptions) {
	p := proto.Clone(in).(*Backend_Destination_ServicePort_ProtocolOptions_MCPOptions)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_ProtocolOptions_MCPOptions. Required by controller-gen.
func (in *Backend_Destination_ServicePort_ProtocolOptions_MCPOptions) DeepCopy() *Backend_Destination_ServicePort_ProtocolOptions_MCPOptions {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_ServicePort_ProtocolOptions_MCPOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_ServicePort_ProtocolOptions_MCPOptions. Required by controller-gen.
func (in *Backend_Destination_ServicePort_ProtocolOptions_MCPOptions) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Extension within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Extension) DeepCopyInto(out *Backend_Extension) {
	p := proto.Clone(in).(*Backend_Extension)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Extension. Required by controller-gen.
func (in *Backend_Extension) DeepCopy() *Backend_Extension {
	if in == nil {
		return nil
	}
	out := new(Backend_Extension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Extension. Required by controller-gen.
func (in *Backend_Extension) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
