// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Backend within kubernetes types, where deepcopy-gen is used.
func (in *Backend) DeepCopyInto(out *Backend) {
	p := proto.Clone(in).(*Backend)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend. Required by controller-gen.
func (in *Backend) DeepCopy() *Backend {
	if in == nil {
		return nil
	}
	out := new(Backend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend. Required by controller-gen.
func (in *Backend) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination) DeepCopyInto(out *Backend_Destination) {
	p := proto.Clone(in).(*Backend_Destination)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination. Required by controller-gen.
func (in *Backend_Destination) DeepCopy() *Backend_Destination {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination. Required by controller-gen.
func (in *Backend_Destination) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_FullyQualifiedDomainName within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_FullyQualifiedDomainName) DeepCopyInto(out *Backend_Destination_FullyQualifiedDomainName) {
	p := proto.Clone(in).(*Backend_Destination_FullyQualifiedDomainName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_FullyQualifiedDomainName. Required by controller-gen.
func (in *Backend_Destination_FullyQualifiedDomainName) DeepCopy() *Backend_Destination_FullyQualifiedDomainName {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_FullyQualifiedDomainName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_FullyQualifiedDomainName. Required by controller-gen.
func (in *Backend_Destination_FullyQualifiedDomainName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_BackendPort within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_BackendPort) DeepCopyInto(out *Backend_Destination_BackendPort) {
	p := proto.Clone(in).(*Backend_Destination_BackendPort)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort. Required by controller-gen.
func (in *Backend_Destination_BackendPort) DeepCopy() *Backend_Destination_BackendPort {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_BackendPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort. Required by controller-gen.
func (in *Backend_Destination_BackendPort) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_BackendPort_TLS within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_BackendPort_TLS) DeepCopyInto(out *Backend_Destination_BackendPort_TLS) {
	p := proto.Clone(in).(*Backend_Destination_BackendPort_TLS)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_TLS. Required by controller-gen.
func (in *Backend_Destination_BackendPort_TLS) DeepCopy() *Backend_Destination_BackendPort_TLS {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_BackendPort_TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_TLS. Required by controller-gen.
func (in *Backend_Destination_BackendPort_TLS) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_BackendPort_TLS_CertificateReference within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_BackendPort_TLS_CertificateReference) DeepCopyInto(out *Backend_Destination_BackendPort_TLS_CertificateReference) {
	p := proto.Clone(in).(*Backend_Destination_BackendPort_TLS_CertificateReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_TLS_CertificateReference. Required by controller-gen.
func (in *Backend_Destination_BackendPort_TLS_CertificateReference) DeepCopy() *Backend_Destination_BackendPort_TLS_CertificateReference {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_BackendPort_TLS_CertificateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_TLS_CertificateReference. Required by controller-gen.
func (in *Backend_Destination_BackendPort_TLS_CertificateReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_BackendPort_TLS_CABundleReference within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_BackendPort_TLS_CABundleReference) DeepCopyInto(out *Backend_Destination_BackendPort_TLS_CABundleReference) {
	p := proto.Clone(in).(*Backend_Destination_BackendPort_TLS_CABundleReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_TLS_CABundleReference. Required by controller-gen.
func (in *Backend_Destination_BackendPort_TLS_CABundleReference) DeepCopy() *Backend_Destination_BackendPort_TLS_CABundleReference {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_BackendPort_TLS_CABundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_TLS_CABundleReference. Required by controller-gen.
func (in *Backend_Destination_BackendPort_TLS_CABundleReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_BackendPort_ProtocolOptions within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_BackendPort_ProtocolOptions) DeepCopyInto(out *Backend_Destination_BackendPort_ProtocolOptions) {
	p := proto.Clone(in).(*Backend_Destination_BackendPort_ProtocolOptions)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_ProtocolOptions. Required by controller-gen.
func (in *Backend_Destination_BackendPort_ProtocolOptions) DeepCopy() *Backend_Destination_BackendPort_ProtocolOptions {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_BackendPort_ProtocolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_ProtocolOptions. Required by controller-gen.
func (in *Backend_Destination_BackendPort_ProtocolOptions) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Destination_BackendPort_ProtocolOptions_MCPOptions within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Destination_BackendPort_ProtocolOptions_MCPOptions) DeepCopyInto(out *Backend_Destination_BackendPort_ProtocolOptions_MCPOptions) {
	p := proto.Clone(in).(*Backend_Destination_BackendPort_ProtocolOptions_MCPOptions)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_ProtocolOptions_MCPOptions. Required by controller-gen.
func (in *Backend_Destination_BackendPort_ProtocolOptions_MCPOptions) DeepCopy() *Backend_Destination_BackendPort_ProtocolOptions_MCPOptions {
	if in == nil {
		return nil
	}
	out := new(Backend_Destination_BackendPort_ProtocolOptions_MCPOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Destination_BackendPort_ProtocolOptions_MCPOptions. Required by controller-gen.
func (in *Backend_Destination_BackendPort_ProtocolOptions_MCPOptions) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Backend_Extension within kubernetes types, where deepcopy-gen is used.
func (in *Backend_Extension) DeepCopyInto(out *Backend_Extension) {
	p := proto.Clone(in).(*Backend_Extension)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Extension. Required by controller-gen.
func (in *Backend_Extension) DeepCopy() *Backend_Extension {
	if in == nil {
		return nil
	}
	out := new(Backend_Extension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Backend_Extension. Required by controller-gen.
func (in *Backend_Extension) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
